import aiohttp
import aiofiles
import pandas as pd
import json
import datetime
import logging
from dataclasses import dataclass
from html.parser import HTMLParser
from geopy import Nominatim, Location
from typing import Optional, NamedTuple, Any, Union, Literal, List, Tuple

USER_AGENT = "(NWSMonitor/debug, nategreenwell@live.com)"
BASE_URL_IEM = "https://mesonet.agron.iastate.edu"
BASE_API_PATH_IEM = "/api/1"
AUTOPLOT_PATH_IEM = "/plotting/auto"
BASE_URL_NWS = "https://api.weather.gov"
NWS_DATA_FORMAT = "application/ld+json"
_log = logging.getLogger(__name__)


@dataclass
class ActiveAlertsCount:
    total: int = 0
    land: int = 0
    marine: int = 0
    regions: dict = None
    areas: dict = None
    zones: dict = None

    def __init__(
        self,
        total: int = 0,
        land: int = 0,
        marine: int = 0,
        regions: dict = None,
        areas: dict = None,
        zones: dict = None,
    ) -> None:
        self.total = total
        self.land = land
        self.marine = marine
        if regions is None:
            self.regions = {}
        else:
            self.regions = regions
        if areas is None:
            self.areas = {}
        else:
            self.areas = areas
        if zones is None:
            self.zones = {}
        else:
            self.zones = zones

    def __repr__(self) -> str:
        return f"Total alerts: {self.total}. Land alerts: {self.land}. Marine alerts: {self.marine}."

    def __str__(self) -> str:
        return repr(self)


class Point(NamedTuple):
    lat: float
    lon: float


class AutoplotParser(HTMLParser):
    """
    This class has one purpose: To find the image generated by using
    IEM's autoplot function.
    """

    _img_url = None

    def handle_starttag(self, tag, attrs):
        if tag == "img":
            if ("id", "theimage") in attrs:
                for attr, val in attrs:
                    if attr == "src":
                        self._img_url = val
                        break

    def reset(self):
        super().reset()
        self._img_url = None

    @property
    def img_url(self):
        return self._img_url


async def check_status(response: aiohttp.ClientResponse) -> None:
    if response.status not in {200, 301}:
        details = await response.json()
        headers = response.headers
        raise RuntimeError(f"Status {response.status}. {details=}; {headers=}")


async def fetch(
    client: aiohttp.ClientSession,
    api_call: str,
    accept: Optional[str] = None,
    no_cache: bool = False,
    **kwargs,
) -> Any:
    headers = {"User-Agent": USER_AGENT}
    if accept:
        headers["Accept"] = accept
    if no_cache:
        headers["Cache-Control"] = "no-cache"
    _log.debug(f"Fetching {client._base_url}{api_call} with {headers=} and {kwargs=}")
    async with client.get(
        api_call,
        params=kwargs,
        headers=headers,
        raise_for_status=check_status,
        timeout=aiohttp.ClientTimeout(total=60),
    ) as resp:
        _log.debug(f"Response headers: {resp.headers}")
        try:
            return await resp.json()
        except aiohttp.ClientResponseError:
            return await resp.text()


async def fetch_autoplot(
    number: int = 220,
    no_cache: bool = False,
    date: Optional[datetime.datetime] = None,
    **kwargs,
) -> None:
    headers = {"User-Agent": USER_AGENT}

    # Delete kwargs that are set to None
    to_delete = set()
    for kwarg, val in kwargs.items():
        if val is None:
            to_delete.add(kwarg)
    for kwarg in to_delete:
        del kwargs[kwarg]

    if no_cache:
        kwargs["_cb"] = 1
    kwargs["q"] = number
    if date:
        kwargs["valid"] = date.strftime("%Y/%m/%d+%H%M")

    async with aiohttp.ClientSession(
        base_url=BASE_URL_IEM, raise_for_status=True
    ) as session:
        parser = AutoplotParser()
        async with session.get(
            AUTOPLOT_PATH_IEM,
            params=kwargs,
            headers=headers,
            raise_for_status=check_status,
            timeout=aiohttp.ClientTimeout(total=60),
        ) as resp:
            _log.debug(f"Response headers: {resp.headers}")
            text = await resp.text()
            async with aiofiles.open("debug.html", "w") as fp:
                await fp.write(text)
            parser.reset()
            parser.feed(text)
            if parser.img_url is None:
                raise RuntimeError(
                    "Autoplot request succeeded but the image was not found."
                )

        async with session.get(
            parser.img_url,
            raise_for_status=check_status,
            timeout=aiohttp.ClientTimeout(total=60),
        ) as resp:
            async with aiofiles.open("autoplot.png", "wb") as img:
                await img.write(await resp.read())


def locate(address: str) -> Tuple[Point, Location]:
    geolocator = Nominatim(user_agent=USER_AGENT)
    location = geolocator.geocode(address, country_codes="us", timeout=20)
    if location is None:
        raise RuntimeError(f"Could not geolocate {address} within the US.")
    return Point(location.latitude, location.longitude), location


async def afos(
    cccc: Optional[str] = None,
    pil: Optional[str] = None,
    date: Optional[datetime.date] = None,
) -> pd.DataFrame:
    params = dict()
    if not (cccc or pil):
        raise ValueError("Either cccc or pil must be set.")

    if cccc:
        params["cccc"] = cccc

    if pil:
        params["pil"] = pil

    if date:
        params["date"] = date.isoformat()

    async with aiohttp.ClientSession(
        base_url=BASE_URL_IEM, raise_for_status=True
    ) as session:
        data = await fetch(session, f"{BASE_API_PATH_IEM}/nws/afos/list.json", **params)
        if not isinstance(data, dict):
            raise RuntimeError(f"Expected a dict, got {type(data).__name__}.")
        return pd.DataFrame(data["data"])


async def nwstext(pid: str) -> str:
    async with aiohttp.ClientSession(
        base_url=BASE_URL_IEM, raise_for_status=True
    ) as session:
        data = await fetch(session, f"{BASE_API_PATH_IEM}/nwstext/{pid}")
        return data


async def active_alerts_count() -> ActiveAlertsCount:
    async with aiohttp.ClientSession(
        base_url=BASE_URL_NWS, raise_for_status=check_status
    ) as session:
        data = await fetch(session, f"/alerts/active/count")
        return ActiveAlertsCount(
            data["total"],
            data["land"],
            data["marine"],
            data["regions"],
            data["areas"],
            data["zones"],
        )


async def alerts(
    *,
    active: bool = True,
    start: Optional[datetime.datetime] = None,
    end: Optional[datetime.datetime] = None,
    status: Optional[
        List[Literal["actual", "exercise", "system", "test", "draft"]]
    ] = None,
    message_type: Optional[List[Literal["alert", "update", "cancel"]]] = None,
    event: Optional[List[str]] = None,
    code: Optional[List[str]] = None,
    area: Optional[List[str]] = None,
    point: Optional[Tuple[float, float]] = None,
    region: Optional[List[Literal["AL", "AT", "GL", "GM", "PA", "PI"]]] = None,
    region_type: Optional[Literal["land", "marine"]] = None,
    zone: Optional[List[str]] = None,
    urgency: Optional[
        List[Literal["Immediate", "Expected", "Future", "Past", "Unknown"]]
    ] = None,
    severity: Optional[
        List[Literal["Extreme", "Severe", "Moderate", "Minor", "Unknown"]]
    ] = None,
    certainty: Optional[
        List[Literal["Observed", "Likely", "Possible", "Unlikely", "Unknown"]]
    ] = None,
    cursor: Optional[str] = None,
    **kwargs,
) -> pd.DataFrame:
    params = {}
    if active:
        api_call = "/alerts/active"
    else:
        api_call = "/alerts"
        if start:
            if start.tzinfo is None:
                raise ValueError("A time zone must be specified.")
            params["start"] = start.isoformat()
        if end:
            if end.tzinfo is None:
                raise ValueError("A time zone must be specified.")
            params["end"] = end.isoformat()

    if status:
        params["status"] = status
    if message_type:
        params["message_type"] = message_type
    if event:
        params["event"] = event
    if code:
        params["code"] = code
    if area:
        params["area"] = area
    if point:
        params["point"] = f"{point[0]},{point[1]}"
    if region:
        params["region"] = region
    if region_type:
        params["region_type"] = region
    if zone:
        params["zone"] = zone
    if urgency:
        params["urgency"] = urgency
    if severity:
        params["severity"] = severity
    if certainty:
        params["certainty"] = certainty
    if cursor:
        params["cursor"] = cursor

    async with aiohttp.ClientSession(
        base_url=BASE_URL_NWS, raise_for_status=check_status
    ) as session:
        data = await fetch(session, api_call, NWS_DATA_FORMAT, **params)
        return pd.DataFrame(data["@graph"])


async def alerts_for_location(address: str, **kwargs) -> pd.DataFrame:
    point = locate(address)[0]
    return await alerts(point=point, **kwargs)


async def glossary() -> pd.DataFrame:
    async with aiohttp.ClientSession(
        base_url=BASE_URL_NWS, raise_for_status=check_status
    ) as session:
        data = await fetch(session, "/glossary")
        return pd.DataFrame(data["glossary"])


async def point_forecast(
    point: Tuple[float, float], units: Optional[Literal["us", "si"]] = "us"
) -> Tuple[Any, pd.DataFrame]:
    async with aiohttp.ClientSession(
        base_url=BASE_URL_NWS, raise_for_status=check_status
    ) as session:
        html_point = f"{point[0]},{point[1]}"
        data = await fetch(session, f"/points/{html_point}", NWS_DATA_FORMAT)
        wfo = data["cwa"]
        x = data["gridX"]
        y = data["gridY"]
        gridpoint = f"/gridpoints/{wfo}/{x},{y}"
        forecast = await fetch(
            session, f"{gridpoint}/forecast", NWS_DATA_FORMAT, units=units
        )
        stations = await fetch(session, f"{gridpoint}/stations", NWS_DATA_FORMAT)
        stations = pd.DataFrame(stations["@graph"])
        station = stations["stationIdentifier"][0]
        obs = await fetch(
            session,
            f"/stations/{station}/observations/latest",
            NWS_DATA_FORMAT,
            require_qc="false",
            no_cache=True,
        )
        return obs, pd.DataFrame(forecast["periods"])


async def get_forecast(
    address: str, units: Optional[Literal["us", "si"]] = "us"
) -> Tuple[Any, pd.DataFrame, Location]:
    point, location = locate(address)
    return await point_forecast(point, units) + (location,)


async def ffg(address: str, valid: Optional[datetime.datetime] = None) -> pd.DataFrame:
    params = {}
    point = locate(address)[0]
    params["lon"] = point.lon
    params["lat"] = point.lat
    if valid:
        if valid.tzinfo is None:
            raise ValueError("A time zone must be specified.")
        params["valid"] = valid.isoformat()
    async with aiohttp.ClientSession(
        base_url=BASE_URL_IEM, raise_for_status=True
    ) as session:
        data = await fetch(session, f"{BASE_API_PATH_IEM}/ffg_bypoint.json", **params)
        return pd.DataFrame(data["ffg"])


async def spc_wpc_outlook(
    *,
    day: int = 1,
    type: Union[str, int] = 0,
    cat: Union[str, int] = 0,
    extent: Union[str, int] = 1,
    wfo: str = "LWX",
    fema: int = 3,
    csector: str = "conus",
    valid: Optional[datetime.datetime] = None,
    no_cache: bool = False,
    **kwargs,
):
    """
    Wrapper for IEM Autoplot app #220.
    By default, fetch the current SPC Day 1 Convective Outlook for CONUS.
    """
    type_real = None
    match type:
        case 0 | "conv" | "C" | "Convective":
            type_real = "C"
        case 1 | "fire" | "F" | "Fire Weather":
            type_real = "F"
        case 2 | "ero" | "E" | "Excessive Rainfall":
            type_real = "E"
        case _:
            raise ValueError("Unknown outlook type.")
    which = f"{day}{type_real}"
    cat_real = None
    if type_real == "C":
        match cat:
            case 0 | "categorical":
                cat_real = "categorical"
            case 1 | "tornado":
                cat_real = "tornado"
            case 2 | "hail":
                cat_real = "hail"
            case 3 | "wind":
                cat_real = "wind"
            case _:
                raise ValueError("Invalid outlook category.")
    else:
        cat_real = "categorical"
    t = None
    match extent:
        case 0 | "wfo" | "cwa":
            t = "cwa"
        case 1 | "state" | "sector" | "state/sector":
            t = "state"
        case 2 | "fema" | "fema region":
            t = "fema"
        case _:
            raise ValueError("Invalid extent type.")
    if wfo is None and t == "cwa":
        raise ValueError("You must specify a WFO.")
    if not fema and t == "fema":
        raise ValueError("You must specify a FEMA region number.")
    if csector is None and t == "state":
        raise ValueError("You must specify a state or sector.")
    await fetch_autoplot(
        number=220,
        no_cache=no_cache,
        date=valid,
        which=which,
        cat=cat_real,
        t=t,
        wfo=wfo,
        fema=fema,
        csector=csector,
        **kwargs,
    )
